### ISSUE TITLE
Visualization issue with snap version

### ISSUE THREAD

**Issue by SteMasoli** [BioDynaMo/biodynamo#29]
Hi. 
We are having an issue with the visualization part of the snap version (0.1). 
We have done the installation on 4 different computers: 3 with Mint 18 (based on Ubuntu 16.04 LTS)  and 1 with Ubuntu 16.04 (16.04.3). 3 PCs have AMD graphic cards and 1 nvidia (the Mint box).

The command "biodynamo.paraview" generates the following error on all the machines:
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.biodynamo', please create it with 0700 permissions.
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

Cheers

**Comment by breitwieserCern** [comment]
Hi Stefano, 
Thank you for reporting this issue!
Could you please try if the biodynamo development version works?

```
git clone https://github.com/BioDynaMo/biodynamo
cd biodynamo

# set-up environment
sudo script/install_prerequesites_ubuntu_16.04.sh

# source biodynamo environment
source /opt/biodynamo/biodynamo_dev.env

# run paraview
paraview
```

Cheers, 
Lukas

**Comment by SteMasoli** [comment]
Hi Lukas.
I have just done it, on my Mint 18.3 box and paraview works. Thank you.

Related to it, I have tried to load the results of the "hello world" example,
https://biodynamo.github.io/biodynamo/hello_world/
but i do not have a file with the pvsm extension to pass to paraview. 
The build and run was done with the snap version.

Best
Stefano

**Comment by breitwieserCern** [comment]
Hi Stefano, 

`pvsm` file generation is not part of the snap package yet.
Please install the development version [1].

```
# cd into the biodynamo directory 

# source biodynamo environment
source /opt/biodynamo/biodynamo_dev.env

# build and install biodynamo
mkdir build && cd build
cmake .. && make -j4
sudo make install
```

Visualization is turned off by default. Please see [2] on how to enable it.

Best, 
Lukas

PS: We also have a slack development channel for BioDynaMo. Please let me know if you want to be added.

[1]  https://biodynamo.github.io/biodynamo/installation/#linux_1
[2]  https://biodynamo.github.io/biodynamo/visualization/

**Comment by SteMasoli** [comment]
Hi Lukas. 
Compiled it, on my second mint box, and everything is fine.
The pvsm is generated and paraview shows it.

Now we'll test it with the other examples and guides. 

Best
Stefano

**Comment by breitwieserCern** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix snap package and apply for inclusion in official snap-store](https://trello.com/c/1HQLxWn4/115-fix-snap-package-and-apply-for-inclusion-in-official-snap-store)

**Comment by breitwieserCern** [comment]
We discontinued our snap package support.
Please see our updated installation instructions:
https://biodynamo.github.io/user/installation/
