### ISSUE TITLE
Cells seem to merge or disappear in soma clustering demo 

### ISSUE THREAD

**Issue by zacharynevin-stemcell** [BioDynaMo/biodynamo#308]
**Describe the bug**
The YouTube video of soma clustering ([https://www.youtube.com/watch?v=jlOk_Y3SUHo](https://www.youtube.com/watch?v=jlOk_Y3SUHo)) shows the initial collection of red/blue cells migrating and forming the final cluster.

**To Reproduce**
1. Follow the instructions on this page to build and run the soma clustering demo: [https://biodynamo.org/docs/userguide/soma_clustering/](https://biodynamo.org/docs/userguide/soma_clustering/). Set the number of cells to 32,000 and the number of steps to 6000 (as in the paper).

**Expected behavior**
The expected behaviour is that the simulation will reproduce the YouTube video, where the initial state is the top image and the final state is the bottom image.

![Screen Shot 2023-01-20 at 1 12 02 PM](https://user-images.githubusercontent.com/62976788/213806102-e4cab092-a4a5-48b1-addc-66228b2d63cb.png)

![Screen Shot 2023-01-20 at 1 09 47 PM](https://user-images.githubusercontent.com/62976788/213806123-0fe6dc0d-ed5a-4598-a63a-e9db67b127b1.png)

**Observed Behaviour (and screenshots)**
The observed behaviour was that the initial state would look similar to what appears in the YouTube video, but as the simulation progressed the cells would appear to merge and/or disappear. In the end, the final result appeared to have far less than 32,000 cells.

The top image is the initial state. The middle image is the state 17 steps in (out of 599). The bottom image is the final state.

![Screen Shot 2023-01-20 at 1 08 39 PM](https://user-images.githubusercontent.com/62976788/213806792-3557d598-6bcc-47a2-8cc2-f78609e482db.png)
![Screen Shot 2023-01-20 at 1 08 30 PM](https://user-images.githubusercontent.com/62976788/213806813-13afe3db-e32d-44df-9ee8-91a9d1715e91.png)
![Screen Shot 2023-01-20 at 1 08 45 PM](https://user-images.githubusercontent.com/62976788/213806832-f0be3324-3f26-4a4e-9e04-a0fcf6da405e.png)

**Setup:**
 - OS: MacOS Montery 12.6.2
 - BioDynaMo version: v1.04.5-e9db03a1

**Additional context**
Does my version of BioDynaMo now require you to explicitly add a mechanical force to prevent the cells from overlapping and occupying the same space?

**Comment by zacharynevin-stemcell** [comment]
Some additional context.

When I change the glyph representation from "Surface" to "Points", I get this:

![Screen Shot 2023-01-20 at 1 27 42 PM](https://user-images.githubusercontent.com/62976788/213808472-d6753a8b-4a65-4aba-82f2-f7c1fd5283b0.png)

It looks like the cell radius (which is set to `10` as per the defaults in the demo) is far smaller than the original YouTube video. The dimensions/scaling appear to be wrong.

**Comment by TobiasDuswald** [comment]
Dear @zacharynevin-stemcell, thanks for reaching out. would you mind zipping your source code (the entire folder) and post it here? 
```
soma_clustering
-- src
---- soma_clustering.h
---- soma_clustering.cc
[...]
```
If you could do that, it should be easy to replicate and we happily investigate that.

**Comment by TobiasDuswald** [comment]
Hi @zacharynevin-stemcell , any update regarding the reproducer zip file? :)

**Comment by zacharynevin-stemcell** [comment]
Hi, sorry I didn't get a notification! I will do this today.

**Comment by zacharynevin-stemcell** [comment]
Hi there,

Here is the compressed soma clustering folder. I ran this on `v1.05.19-c50e1ada` because I wanted to see if a later version would work (I got the same result as above).:

[soma_clustering.zip](https://github.com/BioDynaMo/biodynamo/files/10543021/soma_clustering.zip)

If you need the output as well, I can share a Google Drive file to get past the upload limit.

**Comment by TobiasDuswald** [comment]
Dear @zacharynevin-stemcell ,

Thanks for sharing the reproducer. I haven't worked with the demo myself, so I don't know what it's supposed to look like. But the pictures from the paper differ from the ones you show. On my system, I obtain the same results that you showed so I can reproduce the issue. 

*Few remarks:*
1. The number of cells does not change over time. You can always add a `ResourceManager::GetNumAgents()` after the `simulate` call to obtain the number of agents in the simulation. In this case, it returned 20000, so all good.
2. If you're unsure what operations are scheduled, e.g., wonder if there are mechanical forces, you can call `Scheduler::PrintInfo(std::cout),` and it will tell you what happens.

I listed point two for completeness, but it did not show the mechanical interactions. They are explicitly turned off in 
```
auto set_param = [](Param* param) {
    // Create an artificial bound for the simulation space
    param->bound_space = Param::BoundSpaceMode::kClosed;
    param->min_bound = 0;
    param->max_bound = 250;
    param->unschedule_default_operations = {"mechanical forces"};
  };
```
Frankly, I don't know why, I'm a bit surprised by that. The simulation results look a bit better, though I'd argue there's still quite a significant difference to the "goal". They were turned off by @Senui in 4a7c353. 

@vasvav can you discuss this issue in tomorrow's tech meeting and (make someone) document it here? E.g. what output to expect from the demo and if something needs to be adjusted.

@zacharynevin-stemcell , if you're trying to replicate the results of the BioDynaMo paper, 
you're best advised to check and compare the code submitted with the paper (https://zenodo.org/record/5121618#.Y9kdky2B0eY). The soma clustering demo should definitely work there (most likely even with BDM being the latest master). If that still does not work, consider reaching out to the paper's corresponding author. :)

**Comment by zacharynevin-stemcell** [comment]
Hi @TobiasDuswald, would you be able to share a picture of the simulation results you got when you removed  the line `param->unschedule_default_operations = {"mechanical forces"};`? 

I removed this but the results didn't change for me. The screenshot below shows the final step of the soma clustering simulation, but only with that line removed:

![Screen Shot 2023-01-31 at 4 05 22 PM](https://user-images.githubusercontent.com/62976788/215912703-0eb0c6de-0ebc-493e-ba3d-3152db99a1f5.png)

**Comment by TobiasDuswald** [comment]
Hi @zacharynevin-stemcell , my results looked pretty much like the ones you obtained. They don't match the paper, but they differ from the first image you showed. The tech meeting is today at 11 am CET; I hope somebody gets back to you soon afterward. :)

**Comment by TobiasDuswald** [comment]
We discussed this issue in the Tech meeting, and @UmarAbubacar  will investigate it in more detail. We suspect the parameters differ from the paper use case but have strong reasons to believe everything is alright (besides the parameter choice). @UmarAbubacar will try to reproduce the paper results and get back to you :)

**Comment by zacharynevin-stemcell** [comment]
I have run the simulation from the paper with the parameters they used (see image) on 32K cells and 6K timesteps, version `v1.05.19-c50e1ada`:

![Screen Shot 2023-02-01 at 12 01 51 PM](https://user-images.githubusercontent.com/62976788/216150792-72bb02bb-388f-462e-90f9-236f4915929f.png)

When I do that, the results look slightly better in that the cells aren't merging together so heavily. However, they all migrate into this perfect cube structure.

The picture below is the initial state:
![Screen Shot 2023-02-01 at 12 00 55 PM](https://user-images.githubusercontent.com/62976788/216150925-0e211591-bc19-4169-b3d0-eaa778ce2afc.png)

The picture below is the final state:
![Screen Shot 2023-02-01 at 12 01 12 PM](https://user-images.githubusercontent.com/62976788/216150958-105fb005-5686-4ffa-a70c-884410784edb.png)

**Comment by zacharynevin-stemcell** [comment]
Apologies for all the messages. I think I have reproduced the paper more closely, but still not quite there. I set the max bound to `800` but when I initialized the cells I put them in a `250x250` cube positioned in the centre of the cubic boundary. That eliminated the square edges seen above. 

The picture below shows the final state when I ran that scenario:

![Screen Shot 2023-02-01 at 12 34 19 PM](https://user-images.githubusercontent.com/62976788/216157477-0040a34c-b8f8-4161-b389-6d1311c18dfa.png)

**Comment by TobiasDuswald** [comment]
This should be fixed with PR #313 . If you (@zacharynevin-stemcell ) would like to take a look at it and let us know if the updated results from the demo look better, we'd be very happy. Thank you for your input, feedback, and proactiveness, it's very much appreciated. Helps to make the project even better ;) and thanks @UmarAbubacar for #313! 👍 

If, at some point in the future, you'd like to engage more in the project, consider reaching out to Vasileios or Roman (see biodynamo.org). :)

**Comment by zacharynevin-stemcell** [comment]
I'll take a look today, thanks!

**Comment by zacharynevin-stemcell** [comment]
This looks great, thank you so much! With ray-tracing and shadows enabled, the final result looks like this:

![Screen Shot 2023-02-03 at 9 38 24 AM](https://user-images.githubusercontent.com/62976788/216670320-ec19c25b-08a6-47f7-8b1e-ec04a0e1fb8f.png)

**Comment by TobiasDuswald** [comment]
Amazing, thanks again for reaching out and making us aware of this! I'll close the issue now :)
