### ISSUE TITLE
Connection timed out error

### ISSUE THREAD

**Issue by agoliaei** [BioDynaMo/biodynamo#337]
Hi,
I am trying to install the library using the instructions, but I get the following error. I was wondering if you could help. Is there something I am doing wrong?

curl https://biodynamo.org/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (28) Failed to connect to biodynamo.org port 443: Connection timed out

**Comment by markomanka** [comment]
Thank you for bringing this up.

Try with
curl https://biodynamo.github.io/install | bash

This should solve the issue. We will immediately amend the online instructions as well.

**Comment by agoliaei** [comment]
Thank you!
