### ISSUE TITLE
Website is broken - user guide shows blank page

### ISSUE THREAD

**Issue by pedropgusmao** [BioDynaMo/biodynamo#369]
**Describe the bug**
[User guide web page is not working](https://www.biodynamo.org/user-guide/from-installation-to-1st-steps) 
**To Reproduce**
1. Go to '[BioDynamo](https://www.biodynamo.org/)'
2. Click on 'User-Guide'
3. Scroll down to 'From Installation to 1st step'

**Expected behavior**
A website explaining how to install this tool. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04]
 - BioDynaMo version [e.g. v0.1.0-152-ge3d39e6] (execute command `biodynamo --version`)

**Additional context**

**Comment by TobiasDuswald** [comment]
Dear @pedropgusmao ,

@Senui  was kind enough to fix our website build. For me, it works fine. I hope for you as well?
This should be the page that you were looking for: https://biodynamo.github.io/docs/userguide/installation/ .

T
