### ISSUE TITLE
CentOS System CI freezes at "Run system tests" step

### ISSUE THREAD

**Issue by imorlxs** [BioDynaMo/biodynamo#370]
**Describe the bug**
The centOS System CI throws this error “pml_ucx.c:226 Error: UCP worker does not support MPI_THREAD_MULTIPLE”, and then a bit later it freezes while running the test.

**To Reproduce**
1. Execute "CentOS System CI" action. 

**Expected behavior**
The action to be finishing.

**Setup (please complete the following information):**
 - OS: CentOS Container
 - BioDynaMo version [v1.05.112-2240cece] (latest)

**Comment by TobiasDuswald** [comment]
@LukasBreitwieser @FonsRademakers, what's our take on maintaining the CentOS7 pipeline given that its EOL is set for 30 June?

**Comment by FonsRademakers** [comment]
Should be turned off as CentOS will be unsupported. I’ve the Alma 9 port practically ready, so we can use that for the CI.

Cheers, Fons.

--
Dr. Fons Rademakers
Senior Scientist
CERN - European Organization for Nuclear Research

**Comment by vasvav** [comment]
Indeed, CentOS should be taken off the project - this was discussed (and tentatively agreed) I think 2 or 3 BDM telcos ago.
However, we should add the support for the Ubuntu 24.04 LTS instead of expanding in AlmaLinux OS :) 
cheers
Vas
