### ISSUE TITLE
Deprecated rootcling -c flag, should we get rid of it?

### ISSUE THREAD

**Issue by imorlxs** [BioDynaMo/biodynamo#371]
https://github.com/BioDynaMo/biodynamo/blob/2240cecee52990a4f90c7db9eee13e5d78060b4a/cmake/FindROOT.cmake#L149

According to `rootcling --help`, 
`-c                       - Deprecated, legacy flag which is ignored.`

Should we get rid of it to simplify the code?

**Comment by TobiasDuswald** [comment]
When did they deprecate it? I suppose if it has been deprecated long enough it should be fine. Feel free and try to remove it, if it crashes in the CI then probably one of the OS still needs the `-c`
