### ISSUE TITLE
Discord Invite Invalid on the website

### ISSUE THREAD

**Issue by imorlxs** [BioDynaMo/biodynamo#376]
**Describe the bug**
The Discord invitation is expired

**To Reproduce**
1. Go to https://www.biodynamo.org/user-guide
2. Click on Discord

**Comment by TobiasDuswald** [comment]
Would you be so kind as to take a look, verify, and possibly fix this?
 @vasvav @romanbauer111 @markomanka

**Comment by TobiasDuswald** [comment]
Ping @vasvav @romanbauer111  🔔

**Comment by markomanka** [comment]
To the best of my knowledge there’s no such a link on the website.

Are you talking about the remnants gitpages that I keep hearing will be removed setting up doxygen to output documentation in HTML directly?

I will check the gitpages when I have time… those were meant to be dismissed and only host documentation, not maintained…

M
 


--
Marco Manca, MD
Co-Founder & President
SCImPULSE Foundation <https://www.scimpulse.org/>
Mobile (also Signal): +393484021005
LinkedIn: https://ch.linkedin.com/in/mmanca <https://ch.linkedin.com/in/mmanca>
ORCiD: https://orcid.org/0000-0002-7869-2620 <https://orcid.org/0000-0002-7869-2620>

**Comment by TobiasDuswald** [comment]
<img width="1196" alt="Screenshot 2024-07-22 at 15 37 55" src="https://github.com/user-attachments/assets/5a99901b-be54-4a6c-b436-d2f2ebe7ddc9">


Might be this one?

**Comment by TobiasDuswald** [comment]
https://www.biodynamo.org/user-guide at the very bottom

**Comment by markomanka** [comment]
Edited. Thank you for spotting it!

Marco


--
Marco Manca, MD
Co-Founder & President
SCImPULSE Foundation <https://www.scimpulse.org/>
Mobile (also Signal): +393484021005
LinkedIn: https://ch.linkedin.com/in/mmanca <https://ch.linkedin.com/in/mmanca>
ORCiD: https://orcid.org/0000-0002-7869-2620 <https://orcid.org/0000-0002-7869-2620>

**Comment by TobiasDuswald** [comment]
thanks all!
