### ISSUE TITLE
vtkCPDataDescription.h is not found 

### ISSUE THREAD

**Issue by yixiannanmo** [BioDynaMo/biodynamo#399]
**Describe the bug**
 vtkCPDataDescription.h is not found in the file vtk_agent.h

**To Reproduce**
I used cmake to compile biodynamo
1. cmake -DCMAKE_INSTALL_PREFIX=/opt/biodynamo/install -S ./biodynamo -B build
2. cmake --build build -j 20 --target install

**Expected behavior**
the  vtkCPDataDescription.h is not found in the file vtk_agent.h Maybe it has the mistake from the "#include <vtkCPDataDescription.h>" 

And I used the cmake -Dparaview=OFF,it dismissed.

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04
 - BioDynaMo version: v1.05.119-a4ff3934

**Comment by TobiasDuswald** [comment]
Hi @yixiannanmo 

From your description I can not really tell what's wrong other than that something in the build system fails. can you try the following:

```bash
cd ~/
mkdir biodynamo-test
cd biobiodynamo-test
git clone https://github.com/BioDynaMo/biodynamo.git
cd biodynamo
./prerequisites.sh all.   # skip if you have done this already
mkdir build
cd build
cmake .. | tee cmake.log
make -j 10 | tee make.log
```
If the build fails, please send us the `cmake.log` and `make.log` file that you have just created.

If not, test your build
```
cd biodynamo-test/biodynamo/build
. bin/thisbdm.sh
cd biodynamo-test
bdm demo
bdm demo <specify-demo>
cd <specify-demo>
bdm run
```

**Comment by yixiannanmo** [comment]
The error is attached to the make.log  
[make.log](https://github.com/user-attachments/files/17164259/make.log)


and used the `-Dparaview=OFF` ,it's Ok.
But,when I used `bdm demo diffusion && cd diffusion && bdm run`, the error happened, which is showed in the error.log
[error.log](https://github.com/user-attachments/files/17164233/error.log)

**Comment by TobiasDuswald** [comment]
Can you also send the `cmake.log` such that we can check what happened in the cmake stage?

**Comment by yixiannanmo** [comment]
Of course, The cmake log file is 
[cmake.log](https://github.com/user-attachments/files/17164770/cmake.log)

**Comment by TobiasDuswald** [comment]
Alright, I just went to my remote ubuntu 22.04 machine and checked if the installation works. It indeed works without any problem on the machine.

I send you the logs 
```
cmake .. | tee cmake.log
make -j 10 | tee make.log
```
from my remote machine. I suggest you remove your build folder in biodynamo (`rm -rf <path-to>/biodynamo/build`) and re-run the same commands I used to generate the logs. Then compare you logs line by line to find the difference.

I suspect something goes wrong in the cmake stage but your log is way shorter than mine so I'm not sure if you had run cmake before once.

Also, please do not use the `-Dparaview=off` option, use the default `-Dparaview=on`.
[cmake.log](https://github.com/user-attachments/files/17165084/cmake.log)
[make.log](https://github.com/user-attachments/files/17165086/make.log)

**Comment by TobiasDuswald** [comment]
Did you have any success with that @yixiannanmo ?
