### ISSUE TITLE
Unable to contact

### ISSUE THREAD

**Issue by JohannesFranzMaastricht** [BioDynaMo/biodynamo#46]
Dear BioDynaMo-Team, 

I was trying to send an inquiry via biodynamo-talk@cern.ch (as in https://biodynamo.github.io/user/contact/) but got automatic replies similar to this one:

Delivery has failed to these recipients or groups:
biodynamo-talk@cern.ch
Your message wasn't delivered due to a permission or security issue. It may have been rejected by a moderator, the address may only accept email from certain senders, or another restriction may be preventing delivery.
Diagnostic information for administrators:
Generating server: cern.ch
biodynamo-talk@cern.ch
Remote Server returned '< #5.7.1 smtp;550 5.7.1 RESOLVER.RST.NotAuthorized; not authorized>'

The reason for my inquiry was:
While I am able to use core functionality, I struggle to use BioDynaMos neuroscience module (I am still new to c++ and suspect some namespace-errors on my side).
Would it be possible for you to provide a simple example-script that uses NeuronSoma and NeuriteElement objects (or even a more complex example including custom biology modules)?
(As this is not exactly an issue with the engine, I decided not to make this a separate issue.)

Kind regards, 
Johannes

**Comment by breitwieserCern** [comment]
Hi Johannes, 

Thanks for letting us know and sorry for the inconvenience! 
We have created a new e-mail which fixes that issue (https://biodynamo.github.io/user/contact/)
You can also use my e-mail if you want: lukas DOT breitwieser AT cern DOT ch

I uploaded a new example `pyramidal_cell` demonstrating neurite growth using two biology modules.

Please let me know if you have further questions.
Lukas

**Comment by JohannesFranzMaastricht** [comment]
Hi Lukas, 

Thank you so much, this is very helpful!
I am looking forward to study that example in more detail and will let you know in case of any questions.

Best regards, 
Johannes
